---
name: Test

on: [push]  # yamllint disable-line rule:truthy

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: ["flake8", "yamllint"]
    env:
      TASK_VERSION: 3.32.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: |
          wget https://github.com/go-task/task/releases/download/v$TASK_VERSION/task_linux_amd64.deb
          sudo dpkg -i task_linux_amd64.deb
          task bootstrap
      - name: Run linter ${{ matrix.linter }}
        run: task lint:${{ matrix.linter }}
